version: "3.8"

networks:
  poc-cache:

services:
  redis:
    networks:
      - poc-cache
    image: redis

  redisCommander:
    networks:
      - poc-cache
    depends_on:
      - redis
    ports:
      - '8081:8081'
    image: rediscommander/redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379

  cached-controller:
    networks:
      - poc-cache
    depends_on:
      - redis
    ports:
      - '8080:8080'
    build: .
    container_name: cached-controller
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_CACHE_REDIS_TIMETOLIVE: 10000 # 10sec
